version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_password
      - MYSQL_DATABASE=your_videos_channel_db

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=your_videos_channel_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      default:
        aliases:
          - admin.tradetutorvideo.net

volumes:
  db_data: 