services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./upload:/var/www/html/upload:rw
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
      MYSQL_DATABASE: your_videos_channel_db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_videos_channel_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    cap_add:
      - SYS_NICE
      
  nginx:
    image: nginx:latest
    ports:
      - "801:80"
      # - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ../:/var/www/html
      - ../upload:/var/www/html/upload:rw
    depends_on:
      - app
    networks:
      default:
        aliases:
          - admin.tradetutorvideo.net

volumes:
  mysql_data:
    driver: local 